### PR TITLE
Render trending not following if following 0.

### PR DESCRIPTION
**Pull request by alanpeabody**

### CODE REVIEW

**Comment by alanpeabody** [comment]
Why does the `in progress` label keep getting added?

**Comment by Justin-Holmes** [comment]
@alanpeabody That's a good question, I have no idea. Just checked our Dangerfile and it doesn't appear to be that. I wonder if it's from exploring the different project management tools?

**Comment by alanpeabody** [comment]
oh, I bet it is waffle

**Comment by alanpeabody** [comment]
@Justin-Holmes this all seems right to me... I can't help but wonder if it was just limited staging data that caused problems.

That said, people who's followers have not posted in a while will get a 204. Thoughts on trying to get around that?

**Comment by Justin-Holmes** [comment]
@alanpeabody Sounds good, I'll give it another look.

**Pull request merged**
